[theme]
base                     = "dark"
primaryColor             = "#7c3aed"
backgroundColor          = "#080614"
secondaryBackgroundColor = "#0f0a1e"
textColor                = "#e2e8ff"
font                     = "sans serif"

[server]
headless = true
port = 8501
enableStaticServing = true

[browser]
gatherUsageStats = false
